name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v3

      - run: pnpm install --frozen-lockfile
      - run: pnpm run lint

  test:
    runs-on: ${{ matrix.os }}
    needs: [check]
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node: [16.14, 18]
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v3
        with:
          cache: pnpm
          node-version: ${{ matrix.node }}

      - run: pnpm install --frozen-lockfile
      - run: pnpm run test
